import { Component, signal, effect, OnInit } from '@angular/core';
import { ExamFeesReadDto, ExamFeeCollectionReadDto } from '../../../models/examfeeCollection';
import { ExamfeecollectionService } from '../../../service/examfeecollection-service';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Component({
  selector: 'app-examfees-list',
  standalone: false,
  templateUrl: './examfees-list.html',
  styleUrls: ['./examfees-list.css']
})
export class ExamFeesList implements OnInit {

  examFees = signal<ExamFeesReadDto[]>
    ([]);
  loading = signal(false);
  error = signal('');
  pdfUrl = signal<string | null>(null);

  constructor(private examFeeService: ExamfeecollectionService) { }

  ngOnInit(): void {
    this.loadExamFees();
    effect(() => console.log('Exam Fees updated:', this.examFees()));
  }

  loadExamFees() {
    this.loading.set(true);
    this.examFeeService.getAll().subscribe({
      next: res => { this.examFees.set(res); this.loading.set(false); },
      error: err => { console.error(err); this.error.set('Failed to load exam fees'); this.loading.set(false); }
    });
  }

  getCollected(fee: ExamFeesReadDto): number {
    return fee.feeCollections?.reduce((sum, fc) => sum + fc.examFeeAmount, 0) || 0;
  }

  getDue(fee: ExamFeesReadDto, fc: ExamFeeCollectionReadDto): number {
    return fee.examAmount - fc.examFeeAmount;
  }

  getTotalExamFee(): number {
    return this.examFees()?.reduce((sum, f) => sum + f.examAmount, 0) || 0;
  }

  getTotalCollected(): number {
    return this.examFees()?.reduce((sum, f) => sum + this.getCollected(f), 0) || 0;
  }

  getTotalDue(): number {
    return this.getTotalExamFee() - this.getTotalCollected();
  }

  delete(examFeeId: number) {
    if (!confirm('Are you sure you want to delete this exam fee?')) return;
    this.examFeeService.delete(examFeeId).subscribe({
      next: () => this.examFees.update(fees => fees.filter(f => f.examFeeId !== examFeeId)),
      error: err => { console.error(err); this.error.set('Failed to delete exam fee'); }
    });
  }

  // ✅ Generate Admit Card PDF for a student
  generateAdmitCard(fee: ExamFeesReadDto, student: ExamFeeCollectionReadDto) {
    const doc = new jsPDF('p', 'mm', 'a4');

    // ---------------- Header ----------------
    doc.setFillColor(0, 123, 255); // blue header
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Halishahar Mohila Madrasah', 105, 20, { align: 'center' });
    doc.setFontSize(14);
    doc.text('Admit Card', 105, 28, { align: 'center' });

    // ---------------- Student Info Table ----------------
    const info = [
      ['Student Name', student.studentName],
      ['Roll Number', student.studentId.toString()],
      ['Class', fee.className],
      ['Total Subjects', student.totalSubject.toString()],
      ['Exam Fee Amount', student.examFeeAmount.toString()],
      ['Exam', fee.examName]
    ];

    autoTable(doc, {
      startY: 40,
      head: [['Field', 'Details']],
      body: info,
      styles: {
        font: 'helvetica',
        fontSize: 12,
        cellPadding: 4
      },
      headStyles: {
        fillColor: [0, 123, 255],
        textColor: 255,
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240]
      },
      tableLineWidth: 0.5,
      tableLineColor: 0
    });

    // ---------------- Footer ----------------
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('This admit card is generated by Halishahar Mohila Madrasah', 105, 280, { align: 'center' });

    // ---------------- Open in new tab for printing ----------------
    doc.output('dataurlnewwindow'); // <-- opens PDF in a new browser tab
  }
  viewReport(feeId: number) {
    this.examFeeService.getReport(feeId).subscribe(blob => {
      const fileURL = URL.createObjectURL(blob);
      this.pdfUrl.set(fileURL); // signal holds the blob URL
      window.open(fileURL); // open in a new tab
    }, error => {
      console.error('Failed to load report', error);
    });
  }


}
